---
name: 01 Basic Docker Build
# simplest workflow possible

# Kick of on events (Will kick off whenever we push and commit to a pull_request
# or if you push to the main branch)
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3 # action, name of the action, and version of the action
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker build
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: bretfisher/docker-ci-automation:latest,bretfisher/docker-ci-automation:01
